//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkTankJobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_email_templates
    {
        public int email_template_id { get; set; }
        public string content { get; set; }
        public string subject { get; set; }
        public System.DateTime modified_on { get; set; }
        public string @for { get; set; }
        public string languagecode { get; set; }
        public string type { get; set; }
        public string short_name { get; set; }
        public string sms_content { get; set; }
        public bool status { get; set; }
    }
}
