//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkTankJobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_logs
    {
        public long log_id { get; set; }
        public string description { get; set; }
        public string short_description { get; set; }
        public string msg_function { get; set; }
        public string msg_type { get; set; }
        public string status { get; set; }
        public string error_code { get; set; }
        public string error_description { get; set; }
        public string transaction_ref_id { get; set; }
        public string function_name { get; set; }
        public string stack_trace { get; set; }
        public string trace_data { get; set; }
        public string user_Identifier { get; set; }
        public string ipaddress { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
