//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkTankJobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_login_details
    {
        public long login_detail_id { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public Nullable<System.DateTime> registered_on { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<short> login_failed_count { get; set; }
        public Nullable<bool> login_locked { get; set; }
        public string last_accessed_from { get; set; }
        public string last_used_token { get; set; }
        public Nullable<long> registered_user_id { get; set; }
    
        public virtual tb_registered_users tb_registered_users { get; set; }
    }
}
