//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkTankJobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_multiple_jobs
    {
        public long multiple_jobs_id { get; set; }
        public long registered_user_id { get; set; }
        public long employee_id { get; set; }
        public System.DateTime applied_date { get; set; }
        public long jobs_details_id { get; set; }
    }
}
