//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkTankJobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_registered_users
    {
        public tb_registered_users()
        {
            this.tb_login_details = new HashSet<tb_login_details>();
            this.tb_registered_users_registration_tokens = new HashSet<tb_registered_users_registration_tokens>();
            this.tb_registered_users_resetpasswordtokens = new HashSet<tb_registered_users_resetpasswordtokens>();
        }
    
        public long registered_user_id { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email_address { get; set; }
        public string gender { get; set; }
        public string mobile_country_code { get; set; }
        public string mobile_number { get; set; }
        public System.DateTime registred_on { get; set; }
        public string registration_ip { get; set; }
        public bool is_active { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public Nullable<bool> isEmployer { get; set; }
        public string Organization { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<tb_login_details> tb_login_details { get; set; }
        public virtual ICollection<tb_registered_users_registration_tokens> tb_registered_users_registration_tokens { get; set; }
        public virtual ICollection<tb_registered_users_resetpasswordtokens> tb_registered_users_resetpasswordtokens { get; set; }
    }
}
