//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkTankJobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_registered_users_resetpasswordtokens
    {
        public long password_token_id { get; set; }
        public long registered_user_id { get; set; }
        public string password_token { get; set; }
        public System.DateTime created_on { get; set; }
        public string ip_origin { get; set; }
        public bool is_active { get; set; }
        public System.DateTime expires_on { get; set; }
        public string used_on_origin { get; set; }
        public Nullable<System.DateTime> used_datetime { get; set; }
    
        public virtual tb_registered_users tb_registered_users { get; set; }
    }
}
