//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkTankJobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_smtp_settings
    {
        public short smtp_setting_id { get; set; }
        public string address { get; set; }
        public int port { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public bool use_anonymous { get; set; }
        public bool active { get; set; }
        public string from_address { get; set; }
        public int smtp_type { get; set; }
        public System.DateTime last_modified_on { get; set; }
        public string last_modified_by { get; set; }
        public bool status { get; set; }
        public Nullable<bool> use_https { get; set; }
    }
}
